# CC = g++
# CFLAGS = -g -Wall

# # dequeaslistdriver: dequeaslistdriver.o deque.o 
# # 	$(CC)$(CFLAGS) -o dequeaslistdriver dequeaslistdriver.o deque.o
	
# dequeaslistdriver.o: dequeaslistdriver.cpp deque.h
# 	$(CC)$(CFLAGS) -c dequeaslistdriver.cpp

# deque.o: deque.h


all: dequeaslistdriver.cpp deque.cpp

	g++ dequeaslistdriver.cpp deque.cpp